name: xtract
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - os
  - subprocess
  - uuid
  - urllib
  - json
  - tqdm
  - numpy
  - pandas
  - pynrrd
  - nibabel
  - pynrrd
  - apscheduler
  - flask
  - flask_wtf
  - wtforms